name: build-docker-image-push
on: 
  push:
    branches:
    - main
jobs:
  push-build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "Hello, ${{ github.actor }}!"
      - name: build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/diffusion-flex:${{ github.sha }} . 
      - name: push docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/diffusion-flex:${{ github.sha }}
